### ISSUE TITLE
Be explicit about the babel-cli dependency

### ISSUE THREAD

**Issue by askingalot** [danielstern/redux-saga-sandbox#2] opened 2018-02-18 20:00 UTC
First of all, thank you for your Pluralsight course on redux sagas. It's been very helpful to me.

This might seem like a nit-pick, but when I ran `npm start` on a linux desktop, I got an error because the start script first tries to globally install babel-cli. This fails on my machine because it requires root privileges.

My recommendation is to either add babel-cli as a local dependency or to add instructions for installing it globally in the README.

Thanks, again for the course.

**Comment by danielstern** [comment] 2018-02-19 13:58
Hello!

That's a good suggestion. The problem is that on windows, users can get an error if `babel-cli` is NOT installed globally

Maybe changing things around to run conditionally based on OS might make sense.

**Comment by askingalot** [comment] 2018-02-19 16:28
I think just calling it out in the README would be sufficient. A user who didn't read the README would get an error saying babel-node is not a recognized command and then they'd (hopefully) go back to the README.

**Comment by danielstern** [comment] 2018-02-20 16:47
@askingalot That makes a lot of sense to me. Would you be interested in updating the README and making a quick PR?

**Comment by askingalot** [comment] 2018-02-20 20:12
Sure, I can do that later today or tonight.

**Comment by askingalot** [comment] 2018-04-10 12:58
Was my PR too big of a change?

**Comment by danielstern** [comment] 2018-04-10 15:24
Merged!

**Closed** 2018-04-10 15:26 UTC

**Comment by rubimbura** [comment] 2019-09-20 14:09
I am having problems while trying to use console tab on windows!!!!

**Comment by danielstern** [comment] 2019-09-21 12:54
@rubimbura A number of possible solutions,
1) Try `cmd`
2) Try `powershell`
3) Try a bash script
